#!/usr/bin/env python3
"""
sandbox.py - Jupyter-like sandboxed execution for data analysis.

Runs agent-provided Python analysis scripts in a subprocess with
resource limits, timeouts, and structured output collection.
"""

import os
import sys
import json
import tempfile
import subprocess
import logging
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime, timezone

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(name)s] %(levelname)s: %(message)s')
logger = logging.getLogger("DataSandbox")

# Maximum execution time in seconds
DEFAULT_TIMEOUT = 30
# Maximum output size in bytes
MAX_OUTPUT_BYTES = 1_000_000  # 1 MB


class DataSandbox:
    """
    Sandboxed Python execution environment for data analysis.
    Runs code in an isolated subprocess with timeout enforcement.
    """

    def __init__(self, timeout: int = DEFAULT_TIMEOUT, output_dir: str = None):
        self.timeout = timeout
        self.output_dir = Path(output_dir or tempfile.mkdtemp(prefix="openpango_sandbox_"))
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self._mock = not self._check_deps()

        if self._mock:
            logger.warning("Data dependencies (pandas/numpy) not found. Running in MOCK mode.")

    @staticmethod
    def _check_deps() -> bool:
        """Check if pandas and numpy are available."""
        try:
            result = subprocess.run(
                [sys.executable, "-c", "import pandas; import numpy"],
                capture_output=True, timeout=10
            )
            return result.returncode == 0
        except Exception:
            return False

    def execute(self, code: str, timeout: int = None) -> Dict[str, Any]:
        """
        Execute a Python analysis script in a sandboxed subprocess.

        Args:
            code: Python source code to execute.
            timeout: Override default timeout (seconds).

        Returns:
            Dict with stdout, stderr, exit_code, output_files, and metadata.
        """
        timeout = timeout or self.timeout

        if self._mock:
            return self._mock_execute(code)

        # Write the script to a temporary file inside the output directory
        script_path = self.output_dir / "_analysis_script.py"
        with open(script_path, "w") as f:
            # Inject the output directory so the script can save files there
            f.write(f"import os; os.chdir('{self.output_dir}')\n")
            f.write(code)

        start_time = datetime.now(timezone.utc)

        try:
            result = subprocess.run(
                [sys.executable, str(script_path)],
                capture_output=True,
                timeout=timeout,
                cwd=str(self.output_dir),
                env={**os.environ, "MPLBACKEND": "Agg"},  # Non-interactive matplotlib
            )

            stdout = result.stdout.decode("utf-8", errors="replace")[:MAX_OUTPUT_BYTES]
            stderr = result.stderr.decode("utf-8", errors="replace")[:MAX_OUTPUT_BYTES]

            # Collect any output files generated by the script
            output_files = [
                str(f) for f in self.output_dir.iterdir()
                if f.name != "_analysis_script.py" and f.is_file()
            ]

            return {
                "status": "success" if result.returncode == 0 else "error",
                "exit_code": result.returncode,
                "stdout": stdout,
                "stderr": stderr,
                "output_files": output_files,
                "execution_time_ms": int((datetime.now(timezone.utc) - start_time).total_seconds() * 1000),
                "timestamp": start_time.isoformat(),
            }

        except subprocess.TimeoutExpired:
            return {
                "status": "timeout",
                "error": f"Execution exceeded {timeout}s limit",
                "timestamp": start_time.isoformat(),
            }
        except Exception as e:
            return {
                "status": "error",
                "error": str(e),
                "timestamp": start_time.isoformat(),
            }
        finally:
            # Clean up temp script
            if script_path.exists():
                script_path.unlink()

    def _mock_execute(self, code: str) -> Dict[str, Any]:
        """Simulated execution for environments without data dependencies."""
        logger.info(f"[MOCK] Executing {len(code)} chars of analysis code...")
        return {
            "status": "success_mock",
            "exit_code": 0,
            "stdout": json.dumps({
                "mock_result": True,
                "summary": "Mock analysis completed. Install pandas/numpy for real execution.",
                "rows_processed": 1000,
                "columns": ["id", "value", "category"],
            }),
            "stderr": "",
            "output_files": [],
            "execution_time_ms": 42,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="OpenPango Data Analysis Sandbox")
    parser.add_argument("script", nargs="?", help="Path to a Python script to execute")
    parser.add_argument("--code", help="Inline Python code to execute")
    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT)
    args = parser.parse_args()

    sandbox = DataSandbox(timeout=args.timeout)

    if args.script:
        with open(args.script) as f:
            code = f.read()
    elif args.code:
        code = args.code
    else:
        print("Provide either a script path or --code argument.")
        sys.exit(1)

    result = sandbox.execute(code)
    print(json.dumps(result, indent=2))
